---
ID: "6f97cdde-1bd0-45fa-90ae-b256c900dced"
Parent: "211a1c6e-bfe0-4e9b-8154-17547135adf3"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/Hackathon/meetup/Presentation/Rendering Variants/JSON List/Default
DB: master
BranchID: "08c12327-7685-4c17-bfca-6aae7a55f4c5"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{6E634FCA-8F4D-43E1-ADDD-5A26706605DF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T092058Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
