---
ID: "30f6ba64-138f-44b4-a023-6d560b335b0e"
Parent: "8f9471cd-dace-4c4c-b3bf-fb05e0c29b14"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Hackathon/meetup/Presentation/Rendering Variants/Link List/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C5678F86-D23D-41CA-B236-A1989FCFDAC7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T092122Z
