---
ID: "cc3772a9-4d99-469d-9ea3-b63b0f11b2bc"
Parent: "64d069ad-eaf2-4f1b-bc93-4867b361d7d5"
Template: "64d069ad-eaf2-4f1b-bc93-4867b361d7d5"
Path: /sitecore/templates/Project/Hackathon/Page Designs/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {D1F7D303-56D1-44FE-AC33-C10896EC80F1}
    {97F4DE23-5933-4771-AB2A-7C79BBA3BBF9}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T091135Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
